# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/EBAZ4205_PS2mouse/Vivado/Vivado.srcs/sources_1/bd/ebaz4205/ip/ebaz4205_auto_pc_0/ebaz4205_auto_pc_0.xci
# IP: The module: 'ebaz4205_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EBAZ4205_PS2mouse/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ip/ebaz4205_auto_pc_0/ebaz4205_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/EBAZ4205_PS2mouse/Vivado/Vivado.srcs/sources_1/bd/ebaz4205/ip/ebaz4205_auto_pc_0/ebaz4205_auto_pc_0.xci
# IP: The module: 'ebaz4205_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EBAZ4205_PS2mouse/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ip/ebaz4205_auto_pc_0/ebaz4205_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
