# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/ebaz4205.xdc

# Block Designs: bd/ebaz4205/ebaz4205.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205 || ORIG_REF_NAME==ebaz4205} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_clk_wiz_0_0/ebaz4205_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_clk_wiz_0_0 || ORIG_REF_NAME==ebaz4205_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_0/ebaz4205_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_0 || ORIG_REF_NAME==ebaz4205_xlslice_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_1_0/ebaz4205_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_1_0 || ORIG_REF_NAME==ebaz4205_xlslice_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_0/ebaz4205_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_proc_sys_reset_0_0 || ORIG_REF_NAME==ebaz4205_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_processing_system7_0_0/ebaz4205_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_processing_system7_0_0 || ORIG_REF_NAME==ebaz4205_processing_system7_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_0/ebaz4205_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_0 || ORIG_REF_NAME==ebaz4205_xlconcat_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_interconnect_0_0/ebaz4205_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_interconnect_0_0 || ORIG_REF_NAME==ebaz4205_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_DivideBy2N_0_0/ebaz4205_DivideBy2N_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_DivideBy2N_0_0 || ORIG_REF_NAME==ebaz4205_DivideBy2N_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_counter26_0_0/ebaz4205_counter26_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_counter26_0_0 || ORIG_REF_NAME==ebaz4205_counter26_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_ps2_mouse_0_0/ebaz4205_ps2_mouse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_ps2_mouse_0_0 || ORIG_REF_NAME==ebaz4205_ps2_mouse_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xbar_0/ebaz4205_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xbar_0 || ORIG_REF_NAME==ebaz4205_xbar_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_0_0 || ORIG_REF_NAME==ebaz4205_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_1/ebaz4205_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_1 || ORIG_REF_NAME==ebaz4205_xlconcat_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_auto_pc_0/ebaz4205_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_auto_pc_0 || ORIG_REF_NAME==ebaz4205_auto_pc_0} -quiet] -quiet

# XDC: D:/EBAZ4205_PS2mouse/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ebaz4205_ooc.xdc
